# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# Values common to all flavors

debug: true
maxRequestHeaderSize: "8192" # this can be adjusted to deal with larger header sizes such as with passing certs with Keycloak
license:
  organization: "###ZARF_VAR_SOCKETZERO_LICENSE_ORG###"
  key: "###ZARF_VAR_SOCKETZERO_LICENSE_KEY###"
config: "###ZARF_VAR_SOCKETZERO_CONFIG###"
